//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes_Nodes
    {
        public int RouteId { get; set; }
        public int NodeId { get; set; }
        public int IndexNum { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Route Route { get; set; }
    }
}
