//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripPlanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPEntities : DbContext
    {
        public TPEntities()
            : base("name=TPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Routes_Nodes> Routes_Nodes { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<Users_Trips> Users_Trips { get; set; }
    }
}
