//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Trips
    {
        public string UserId { get; set; }
        public int TripId { get; set; }
        public bool Author { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
